Issue60: Hacktoberfest celebration: Blogs: 'Rooster Rescue' by Alexis…
akshitagupta15june/PetMe pull request #284
Opened 2022-10-27 14:25 UTC by LittleMissButtons

## Description

New blog submission for 'Rooster Rescue' by LittleMissButtons (Alexis Pendleton).

## Related Issue

Issue 60: Hacktoberfest celebration: Blogs: 

## Acceptance Criteria

Write a blog on anything related to pet or stray animals: Hacktoberfest

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
| ✓ | :scroll: Docs              |

## Updates

### Before

![image](https://user-images.githubusercontent.com/59650617/198311219-6f2ba673-dbe4-4058-bfde-7ca591844148.png)

### After

![image](https://user-images.githubusercontent.com/59650617/198311655-0dbdb954-2d51-42b6-9a84-3090efa0f59c.png)
![image](https://user-images.githubusercontent.com/59650617/198311854-d76c70e2-2815-4335-9660-1f7f5f116556.png)

- Blog12 card added to the bottom of the 'Blog' page
- Rooster Rescue blog page added
- b12-poster image added for that blog
- Writer added to the Contributions.md

## Testing Steps / QA Criteria

Blog page and new blog at the bottom on the page. Click 'Rooster Rescue' card for the full blog.

2022-10-29 17:41 UTC, Anuran12 requested changes

2022-10-29 17:41 UTC, Anuran12 commented on blogs/alexis.html
> +                <p class="text-[#5b5963] my-[1rem] mx-0 text-xl">‘Has anyone lost a chicken? We’ve one at the shop!’
```suggestion
                <h3 class="text-xl xl:text-2xl font-semibold tracking-wide">‘Has anyone lost a chicken? We’ve one at the shop!’</h3>
```

Do this changes in all your heading points @LittleMissButtons

2022-10-29 17:42 UTC, Anuran12 commented on blogs/alexis.html
> +                <p class="text-[#5b5963] my-[1rem] mx-0 text-xl">‘Has anyone lost a chicken? We’ve one at the shop!’
@LittleMissButtons  Otherwise its all okay.. please quickly change this.

2022-10-29 18:51 UTC, LittleMissButtons commented on blogs/alexis.html
> +                <p class="text-[#5b5963] my-[1rem] mx-0 text-xl">‘Has anyone lost a chicken? We’ve one at the shop!’
Hi, thanks for the feedback and I have updated that now and pushed the changes.

Hopefully that comes through ok. Please could you add the Hacktoberfest-Accepted label to this PR. Cheers

2022-10-30 03:40 UTC, Anuran12 approved these changes
Look good to me

2022-10-30 03:45 UTC, akshitagupta15june approved these changes
thanks @LittleMissButtons and @Anuran12

2022-10-30 03:45 UTC, merged

2022-10-30 03:47 UTC, Anuran12 commented
@akshitagupta15june  I am making another PR within few minutes

2022-10-30 03:48 UTC, akshitagupta15june commented
@Anuran12 can you look at the discord dm , i just dmed you regarding something