Blogs page changes
akshitagupta15june/PetMe pull request #589
Opened 2023-05-23 18:09 UTC by TeekshaHarish

Added favicons to the blog pages

![image](https://github.com/akshitagupta15june/PetMe/assets/102624456/7b778a84-e27c-481e-83c7-ee75cc3711b9)

Properly aligned the READ button on the Blogs Page

![image](https://github.com/akshitagupta15june/PetMe/assets/102624456/b429f300-6de9-4152-ad34-9168708f9526)

Fixed Text alignment on the blog pages

![image](https://github.com/akshitagupta15june/PetMe/assets/102624456/7b51f43b-1a1b-4cb8-a8a8-e84228b13b11)

2023-05-24 10:14 UTC, swethatheresa approved these changes

2023-05-24 15:24 UTC, akshitagupta15june requested changes
mention issue that you are targetting

2023-05-25 18:33 UTC, TeekshaHarish commented
> mention issue that you are targetting

issue #398

2023-06-11 09:32 UTC, akshitagupta15june approved these changes

2023-06-11 09:33 UTC, akshitagupta15june commented
please resolve the conflicts by updating your codebase

2023-06-11 09:33 UTC, closed without merging